package stepdefinitions;

// Generated from Jira issue: QA-101
// Generated by Jira Automation Agent. Re-run the agent to sync Jira Gherkin changes.
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;

public class Qa101ValidUserCanLogInSteps {

    @Given("I launch the browser")
    public void iLaunchTheBrowser() {
        throw new io.cucumber.java.PendingException("Implement step from QA-101");
    }

    @When("I open the login page")
    public void iOpenTheLoginPage() {
        throw new io.cucumber.java.PendingException("Implement step from QA-101");
    }

    @When("I enter username \"admin\" and password \"admin123\"")
    public void iEnterUsernameAdminAndPasswordAdmin123() {
        throw new io.cucumber.java.PendingException("Implement step from QA-101");
    }

    @When("I should see Image")
    public void iShouldSeeImage() {
        throw new io.cucumber.java.PendingException("Implement step from QA-101");
    }

    @Then("I should see the Landing page")
    public void iShouldSeeTheLandingPage() {
        throw new io.cucumber.java.PendingException("Implement step from QA-101");
    }
}
