# Generated from Jira issue: QA-101
# Generated by Jira Automation Agent. Re-run the agent to sync Jira Gherkin changes.
@AutomationCandidate @QA-101
Feature: Valid user can log in

  Scenario: Valid user can log in
    Given I launch the browser
    When I open the login page
    And I enter username "admin" and password "admin123"
    And I should see Image
    Then I should see the Landing page
